name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::479553947752:role/github-actions-ssuareza-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "ssuareza-terraform-statefile"
      aws-lock-dynamodb-table: "ssuareza-terraform-lock"
